### ISSUE TITLE
vite.config.ts  alias 配置问题

### ISSUE THREAD

**Issue by SKT-Shurima** [lichenbuliren/fe-project-base#1]
采用项目中配置，在window环境下跑不起来
`
alias: [
      {
        find: /@\//,
        replacement: path.resolve(__dirname, './src')
      }
    ]
`
改为
`
 alias: {
      '@': path.resolve(__dirname, './src')
    }
`
即可

**Comment by lichenbuliren** [comment]
> 采用项目中配置，在window环境下跑不起来
> `alias: [ { find: /@\//, replacement: path.resolve(__dirname, './src') } ]`
> 改为
> `alias: { '@': path.resolve(__dirname, './src') }`
> 即可

更新了下配置，原来的 `path.resolve` 需要改成 `path.join` 就好了
``` js
alias: [
  {
    find: /@\//,
    replacement: path.join(__dirname, './src/')
  }
]
```
